fix test requirements version go-testing-interface Downgrading github.com/mitchellh/go-testing-interface for supporting previous version Golang v1.13, not only v1.14 This version does not implement `Cleanup` and `Parallel` methods.
##[error]jocko/broker_test.go:446:27: cannot use t (type *"testing".T) as type "github.com/mitchellh/go-testing-interface".T in argument to NewTestServer:
	*"testing".T does not implement "github.com/mitchellh/go-testing-interface".T (missing Cleanup method)